development: &default
  adapter: postgresql
  database: course_level_reference_app_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: course_level_reference_app_test
